name: ddnsb0t

type: go

up:
  - go:
      version: 1.15.5
      modules: true

# `dev run` runs `dev build` and then `dev run-built` if these are both defined.
commands:
  build:
    run: go build -o ddnsb0t
  run-built:
    desc: |
      Run the target after `dev build`.
      `dev run` is a special command that will run `dev build` and then `dev run-built` if they are both defined.
    run: ./ddnsb0t
  test:
    run: go test ./...
  style:
    run: 'golint ./... && errcheck ./...'
